#
# Module manifest for module 'PsCalendar'
#
# Generated by: Scott P. Rudy
#
# Generated on: 3/29/2016
#
@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'PsCalendar.psm1'
    # Version number of this module.
    ModuleVersion = '1.0.0'
    # ID used to uniquely identify this module
    GUID = '6c167c65-b38e-40f3-9d82-12f5544aa43d'
    # Author of this module
    Author = 'Scott P. Rudy'
    # Copyright statement for this module
    Copyright = '(c) 2016 Scott P. Rudy. All rights reserved.'
    # Description of the functionality provided by this module
    Description = 'calendar display'
    # Functions to export from this module
    FunctionsToExport = 'Get-Calendar'
    #Aliases to export from this module
    AliasesToExport  = 'Cal'
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('calendar')
            # A URL to the license for this module.
            LicenseUri = 'http://creativecommons.org/licenses/by-nc/1.0'
            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/scottrudy/PsCalendar'
            # A URL to an icon representing this module.
            IconUri = ''
            # ReleaseNotes of this module
            ReleaseNotes = 'First Version'

        } # End of PSData hashtable

    } # End of PrivateData hashtable
}